#!/bin/sh

export GI_TYPELIB_PATH=$GI_TYPELIB_PATH:/home/server/aravis/src
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.2/lib64:/home/server/aravis/src/.libs

pm2 start snapshotCamerasMainStart.py --interpreter='python3'
