#!/bin/sh

export GI_TYPELIB_PATH=$GI_TYPELIB_PATH:/home/server/aravis/src
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.2/lib64:/home/server/aravis/src/.libs

pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_1' -- CAM_1
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_2' -- CAM_2
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_3' -- CAM_3
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_4' -- CAM_4
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_5' -- CAM_5
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_6' -- CAM_6
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_7' -- CAM_7
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_8' -- CAM_8
pm2 start snapshotCamerasMainStart.py --interpreter='python3' --name='CAM_9' -- CAM_9


